- name: Install + configure Filebeat, ElasticSearch, and Kibana
  user: churusaa
  sudo: True
  hosts: all
  tasks:

  - name: Make sure apt-transport-https is installed 
    apt: 
      name: apt-transport-https 
      state: present
  
  - name: Add Elasticsearch apt key.
    apt_key:
      url: https://packages.elastic.co/GPG-KEY-elasticsearch
      state: present

  - name: Add Kibana repository.
    raw: echo "deb https://artifacts.elastic.co/packages/5.x/apt stable main" | tee -a /etc/apt/sources.list.d/elastic-5.x.list
#    apt_repository:
## apt-add-repository doesn't work for Kibana yet
#      repo: 'deb https://packages.elastic.co/kibana/5.x/debian stable main'
#      state: present
#      update_cache: yes
  - name: Update apt-cache
    apt:
      update_cache: yes   
  - name: Install Kibana
    raw: apt-get install kibana --allow-unauthenticated
#    apt:
#         name: kibana
#         state: latest 
#         allow_unauthenticated: yes

  - name: Install ElasticSearch
    raw: apt-get install elasticsearch --allow-unauthenticated
#    apt: 
#       name: elasticsearch 
#       state: latest
#       allow_unauthenticated: yes 
#  - lineinfile:
#       dest: /etc/apt/sources.list.d/artifacts_elastic_co_packages_5_x_apt.list
#       state: absent
#       line: 

  - name: Install Filebeat
    apt: 
     name: filebeat
     state: latest
  - replace:
     ## Note: Change dest: to path: once Ansible 2.3 changeover confirmed
     dest: /etc/filebeat/filebeat.yml
     regexp: '..paths:[\n].+[\n]'
     replace: '  paths:\n    - /var/log/syslog\n'
     backup: Yes
  
  - ufw:
     state: enabled
     rule: allow
     port: '{{ item }}'
    with_items:
     - 80
     - 443
     - 5601
     - 9300
     - 5044
