- name: Install + configure Filebeat, ElasticSearch, and Kibana
  user: churusaa
  sudo: True
  hosts: all
  tasks:


  - apt_repository: 
      repo: deb https://artifacts.elastic.co/packages/5.x/apt stable main
      state: present
      validate_certs: yes
  - name: Install Kibana
    apt:
       name: kibana
       state: latest 
       allow_unauthenticated: True

  - name: Install ElasticSearch
    apt: 
       name: elasticsearch 
       state: latest
       allow_unauthenticated: True
#  - lineinfile:
#       dest: /etc/apt/sources.list.d/artifacts_elastic_co_packages_5_x_apt.list
#       state: absent
#       line: 

  - name: Install Filebeat
    apt: 
       name: filebeat
       state: latest
  - replace:
       ## Note: Change dest: to path: once Ansible 2.3 changeover confirmed
       dest: /etc/filebeat/filebeat.yml
       regexp: '..paths:[\n].+[\n]'
       replace: '  paths:\n    - /var/log/syslog\n'
       backup: Yes

  - ufw:
      vars:
        open_ports=[80,443,4096]
      state: enabled
      rule: allow
      port: '{{ open_ports }}'
